import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-gray-950`}>
        <div className="bg-red-400 absolute top-0 left-[40%] h-[32rem] w-[32rem] rounded-full blur-[32rem] sm:w-[40rem]"></div>
        <div className="bg-blue-400 absolute top-0 right-[40%] h-[32rem] w-[32rem] rounded-full blur-[32rem] sm:w-[40rem]"></div>

        <Header />
        {children}
      </body>
    </html>
  );
}
